=== XRPLF/xrpl.js/src/common/schemas/output/get-transaction.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "getTransaction",
  "description": "getTransaction response",
  "link": "gettransaction",
  "properties": {
    "type": {
      "$ref": "transactionType"
    },
    "specification": {
      "description": "A specification that would produce the same outcome as this transaction. *Exception:* For payment transactions, this omits the `destination.amount` field, to prevent misunderstanding. The structure of the specification depends on the value of the `type` field (see [Transaction Types](#transaction-types) for details). *Note:* This is **not** necessarily the same as the original specification."
    },
    "outcome": {
      "$ref": "outcome",
      "description": "The outcome of the transaction (what effects it had)."
    },
    "id": {
      "$ref": "transactionHash",
      "description": "A hash of the transaction that can be used to identify it."
    },
    "address": {
      "$ref": "address",
      "description": "The address of the account that initiated the transaction."
    },
    "sequence": {
      "$ref": "sequence",
      "description": "The account sequence number of the transaction for the account that initiated it."
    },
    "rawTransaction": {
      "description": "The raw transaction data as a JSON string. For advanced users only; exercise caution when interpreting this data.",
      "type": "string"
    }
  },
  "required": [
    "id",
    "address",
    "sequence",
    "type",
    "specification",
    "outcome"
  ],
  "additionalProperties": false,
  "oneOf": [
    {
      "properties": {
        "type": {
          "enum": [
            "payment"
          ]
        },
        "specification": {
          "$ref": "getPayment"
        }
      }
    },
    {
      "properties": {
        "type": {
          "enum": [
            "order"
          ]
        },
        "specification": {
          "$ref": "order"
        }
      }
    },
    {
      "properties": {
        "type": {
          "enum": [
            "orderCancellation"
          ]
        },
        "specification": {
          "$ref": "orderCancellation"
        }
      }
    },
    {
      "properties": {
        "type": {
          "enum": [
            "trustline"
          ]
        },
        "specification": {
          "$ref": "trustline"
        }
      }
    },
    {
      "properties": {
        "type": {
          "enum": [
            "settings"
          ]
        },
        "specification": {
          "$ref": "getSettings"
        }
      }
    },
    {
      "properties": {
        "type": {
          "enum": [
            "checkCreate"
          ]
        },
        "specification": {
          "$ref": "checkCreate"
        }
      }
    },
    {
      "properties": {
        "type": {
          "enum": [
            "checkCancel"
          ]
        },
        "specification": {
          "$ref": "checkCancel"
        }
      }
    },
    {
      "properties": {
        "type": {
          "enum": [
            "checkCash"
          ]
        },
        "specification": {
          "$ref": "checkCash"
        }
      }
    },
    {
      "properties": {
        "type": {
          "enum": [
            "escrowCreation"
          ]
        },
        "specification": {
          "$ref": "escrowCreation"
        }
      }
    },
    {
      "properties": {
        "type": {
          "enum": [
            "escrowCancellation"
          ]
        },
        "specification": {
          "$ref": "escrowCancellation"
        }
      }
    },
    {
      "properties": {
        "type": {
          "enum": [
            "escrowExecution"
          ]
        },
        "specification": {
          "$ref": "escrowExecution"
        }
      }
    },
    {
      "properties": {
        "type": {
          "enum": [
            "paymentChannelCreate"
          ]
        },
        "specification": {
          "$ref": "paymentChannelCreate"
        }
      }
    },
    {
      "properties": {
        "type": {
          "enum": [
            "paymentChannelFund"
          ]
        },
        "specification": {
          "$ref": "paymentChannelFund"
        }
      }
    },
    {
      "properties": {
        "type": {
          "enum": [
            "paymentChannelClaim"
          ]
        },
        "specification": {
          "$ref": "paymentChannelClaim"
        }
      }
    }
  ]
}

=== XRPLF/xrpl.js/test/fixtures/responses/getTransactionEscrowCreation.json
{
  "type": "escrowCreation",
  "address": "rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh",
  "sequence": 10,
  "id": "144F272380BDB4F1BD92329A2178BABB70C20F59042C495E10BF72EBFB408EE1",
  "specification": {
    "amount": "0.000002",
    "destination": "rp8rJYTpodf8qbSCHVTNacf8nSW8mRakFw",
    "memos": [
      {
        "type": "x2",
        "format": "text/plain",
        "data": "mema data"
      }
    ],
    "condition": "A0258020E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855810100",
    "allowCancelAfter": "2015-11-16T06:53:42.000Z",
    "allowExecuteAfter": "2015-11-16T06:47:42.000Z",
    "destinationTag": 2,
    "sourceTag": 1
  },
  "outcome": {
    "result": "tesSUCCESS",
    "timestamp": "2015-11-16T06:43:00.000Z",
    "fee": "0.000012",
    "balanceChanges": {
      "rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh": [
        {
          "currency": "XRP",
          "value": "-0.000014"
        }
      ]
    },
    "orderbookChanges": {},
    "ledgerVersion": 15,
    "indexInLedger": 0
  }
}

=== XRPLF/xrpl.js/test/fixtures/responses/get-transaction-order-with-expiration-cancellation.json
{
  "type": "orderCancellation",
  "address": "rBSZe33F5oxHTbxSF1nZJooVDpcrrqNFp3",
  "sequence": 1122979,
  "id": "097B9491CC76B64831F1FEA82EAA93BCD728106D90B65A072C933888E946C40B",
  "specification": {
    "orderSequence": 1122978
  },
  "outcome": {
    "result": "tesSUCCESS",
    "timestamp": "2015-01-14T18:27:00.000Z",
    "fee": "0.011",
    "balanceChanges": {
      "rBSZe33F5oxHTbxSF1nZJooVDpcrrqNFp3": [
        {
          "currency": "XRP",
          "value": "-0.011"
        }
      ]
    },
    "orderbookChanges": {
      "rBSZe33F5oxHTbxSF1nZJooVDpcrrqNFp3": [
        {
          "direction": "buy",
          "quantity": {
            "currency": "CNY",
            "counterparty": "rnuF96W4SZoCJmbHYBFoJZpR8eCaxNvekK",
            "value": "3200"
          },
          "totalPrice": {
            "currency": "XRP",
            "value": "34700.537395"
          },
          "sequence": 1122978,
          "status": "cancelled",
          "makerExchangeRate": "0.09221759200942773",
          "expirationTime": "2015-01-14T18:36:52.000Z"
        }
      ]
    },
    "ledgerVersion": 11119599,
    "indexInLedger": 15
  }
}

=== XRPLF/xrpl.js/test/fixtures/responses/get-transaction-payment-channel-create.json
{
  "type": "paymentChannelCreate",
  "address": "rfAuMkVuZQnQhvdMcUKg4ndBb9SPDhzNmK",
  "sequence": 113,
  "id": "0E9CA3AB1053FC0C1CBAA75F636FE1EC92F118C7056BBEF5D63E4C116458A16D",
  "specification": {
    "amount": "1",
    "destination": "rBmNDZ7vbTCwakKXsX3pDAwDdQuxM7yBRa",
    "sourceTag": 3444675312,
    "publicKey": "EDE059A23CBE00BDD465910EBDA67C86BAD046FA52E1BBBB27159E31980BAFEFB9",
    "settleDelay": 90000
  },
  "outcome": {
    "result": "tesSUCCESS",
    "timestamp": "2017-03-09T14:09:50.000Z",
    "fee": "0.000012",
    "balanceChanges": {
      "rfAuMkVuZQnQhvdMcUKg4ndBb9SPDhzNmK": [
        {
          "currency": "XRP",
          "value": "-1.000012"
        }
      ]
    },
    "orderbookChanges": {},
    "ledgerVersion": 786309,
    "indexInLedger": 0
  }
}

=== XRPLF/xrpl.js/test/fixtures/responses/get-transaction-escrow-cancellation.json
{
  "type": "escrowCancellation",
  "address": "rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh",
  "sequence": 9,
  "id": "F346E542FFB7A8398C30A87B952668DAB48B7D421094F8B71776DA19775A3B22",
  "specification": {
    "owner": "rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh",
    "escrowSequence": 7
  },
  "outcome": {
    "result": "tesSUCCESS",
    "timestamp": "2015-11-16T04:50:20.000Z",
    "fee": "0.000012",
    "balanceChanges": {
      "rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh": [
        {
          "currency": "XRP",
          "value": "-0.00001"
        }
      ]
    },
    "orderbookChanges": {},
    "ledgerVersion": 14,
    "indexInLedger": 0
  }
}

=== XRPLF/xrpl.js/test/fixtures/responses/get-transaction-escrow-execution-simple.json
{
  "type": "escrowExecution",
  "address": "rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh",
  "sequence": 6,
  "id": "CC5277137B3F25EE8B86259C83CB0EAADE818505E4E9BCBF19B1AC6FD1369931",
  "specification": {
    "owner": "rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh",
    "escrowSequence": 5,
    "condition": "632F2F3E437AE720C397994A985B5D21FE186DE61523A9CA3E8709CC581671A1"
  },
  "outcome": {
    "result": "tesSUCCESS",
    "timestamp": "2015-11-17T01:47:40.000Z",
    "fee": "0.000012",
    "balanceChanges": {
      "rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh": [
        {
          "currency": "XRP",
          "value": "-0.000012"
        }
      ],
      "rp8rJYTpodf8qbSCHVTNacf8nSW8mRakFw": [
        {
          "currency": "XRP",
          "value": "10.000043"
        }
      ]
    },
    "orderbookChanges": {},
    "ledgerVersion": 14,
    "indexInLedger": 0
  }
}

=== XRPLF/xrpl.js/test/fixtures/responses/get-transaction-payment-channel-claim.json
{
  "type": "paymentChannelClaim",
  "address": "rBmNDZ7vbTCwakKXsX3pDAwDdQuxM7yBRa",
  "sequence": 99,
  "id": "81B9ECAE7195EB6E8034AEDF44D8415A7A803E14513FDBB34FA984AB37D59563",
  "specification": {
    "channel": "43904CBFCDCEC530B4037871F86EE90BF799DF8D2E0EA564BC8A3F332E4F5FB1",
    "balance": "0.801",
    "publicKey": "EDE059A23CBE00BDD465910EBDA67C86BAD046FA52E1BBBB27159E31980BAFEFB9",
    "signature": "5567FB8A27D8BF0C556D3D31D034476FC04F43846A6613EB4B1B64C396C833600BE251CE3104CF02DA0085B473E02BA0BA21F794FB1DC95DAD702F3EA761CA02"
  },
  "outcome": {
    "result": "tesSUCCESS",
    "timestamp": "2017-03-09T14:09:51.000Z",
    "fee": "0.000012",
    "balanceChanges": {
      "rBmNDZ7vbTCwakKXsX3pDAwDdQuxM7yBRa": [
        {
          "currency": "XRP",
          "value": "0.800988"
        }
      ]
    },
    "orderbookChanges": {},
    "ledgerVersion": 786310,
    "indexInLedger": 0
  }
}

=== XRPLF/xrpl.js/test/fixtures/responses/getTransactionEscrowExecution.json
{
  "type": "escrowExecution",
  "address": "rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh",
  "sequence": 6,
  "id": "CC5277137B3F25EE8B86259C83CB0EAADE818505E4E9BCBF19B1AC6FD136993B",
  "specification": {
    "owner": "rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh",
    "escrowSequence": 5,
    "condition": "A0258020E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855810100",
    "fulfillment": "A0028000"
  },
  "outcome": {
    "result": "tesSUCCESS",
    "timestamp": "2015-11-17T01:47:40.000Z",
    "fee": "0.000012",
    "balanceChanges": {
      "rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh": [
        {
          "currency": "XRP",
          "value": "-0.000012"
        }
      ],
      "rp8rJYTpodf8qbSCHVTNacf8nSW8mRakFw": [
        {
          "currency": "XRP",
          "value": "10.000043"
        }
      ]
    },
    "orderbookChanges": {},
    "ledgerVersion": 14,
    "indexInLedger": 0
  }
}

=== XRPLF/xrpl.js/test/fixtures/responses/get-transaction-payment-channel-fund.json
{
  "type": "paymentChannelFund",
  "address": "rfAuMkVuZQnQhvdMcUKg4ndBb9SPDhzNmK",
  "sequence": 114,
  "id": "CD053D8867007A6A4ACB7A432605FE476D088DCB515AFFC886CF2B4EB6D2AE8B",
  "specification": {
    "channel": "43904CBFCDCEC530B4037871F86EE90BF799DF8D2E0EA564BC8A3F332E4F5FB1",
    "amount": "1"
  },
  "outcome": {
    "result": "tesSUCCESS",
    "timestamp": "2017-03-09T14:09:51.000Z",
    "fee": "0.000012",
    "balanceChanges": {
      "rfAuMkVuZQnQhvdMcUKg4ndBb9SPDhzNmK": [
        {
          "currency": "XRP",
          "value": "-1.000012"
        }
      ]
    },
    "orderbookChanges": {},
    "ledgerVersion": 786310,
    "indexInLedger": 1
  }
}
