=== XRPLF/xrpl.js/src/common/schemas/output/get-transaction.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "getTransaction",
  "description": "getTransaction response",
  "link": "gettransaction",
  "properties": {
    "type": {
      "$ref": "transactionType"
    },
    "specification": {
      "description": "A specification that would produce the same outcome as this transaction. *Exception:* For payment transactions, this omits the `destination.amount` field, to prevent misunderstanding. The structure of the specification depends on the value of the `type` field (see [Transaction Types](#transaction-types) for details). *Note:* This is **not** necessarily the same as the original specification."
    },
    "outcome": {
      "$ref": "outcome",
      "description": "The outcome of the transaction (what effects it had)."
    },
    "id": {
      "$ref": "transactionHash",
      "description": "A hash of the transaction that can be used to identify it."
    },
    "address": {
      "$ref": "address",
      "description": "The address of the account that initiated the transaction."
    },
    "sequence": {
      "$ref": "sequence",
      "description": "The account sequence number of the transaction for the account that initiated it."
    },
    "rawTransaction": {
      "description": "The raw transaction data as a JSON string. For advanced users only; exercise caution when interpreting this data.",
      "type": "string"
    }
  },
  "required": [
    "id",
    "address",
    "sequence",
    "type",
    "specification",
    "outcome"
  ],
  "additionalProperties": false,
  "oneOf": [
    {
      "properties": {
        "type": {
          "enum": [
            "payment"
          ]
        },
        "specification": {
          "$ref": "getPayment"
        }
      }
    },
    {
      "properties": {
        "type": {
          "enum": [
            "order"
          ]
        },
        "specification": {
          "$ref": "order"
        }
      }
    },
    {
      "properties": {
        "type": {
          "enum": [
            "orderCancellation"
          ]
        },
        "specification": {
          "$ref": "orderCancellation"
        }
      }
    },
    {
      "properties": {
        "type": {
          "enum": [
            "trustline"
          ]
        },
        "specification": {
          "$ref": "trustline"
        }
      }
    },
    {
      "properties": {
        "type": {
          "enum": [
            "settings"
          ]
        },
        "specification": {
          "$ref": "getSettings"
        }
      }
    },
    {
      "properties": {
        "type": {
          "enum": [
            "checkCreate"
          ]
        },
        "specification": {
          "$ref": "checkCreate"
        }
      }
    },
    {
      "properties": {
        "type": {
          "enum": [
            "checkCancel"
          ]
        },
        "specification": {
          "$ref": "checkCancel"
        }
      }
    },
    {
      "properties": {
        "type": {
          "enum": [
            "checkCash"
          ]
        },
        "specification": {
          "$ref": "checkCash"
        }
      }
    },
    {
      "properties": {
        "type": {
          "enum": [
            "escrowCreation"
          ]
        },
        "specification": {
          "$ref": "escrowCreation"
        }
      }
    },
    {
      "properties": {
        "type": {
          "enum": [
            "escrowCancellation"
          ]
        },
        "specification": {
          "$ref": "escrowCancellation"
        }
      }
    },
    {
      "properties": {
        "type": {
          "enum": [
            "escrowExecution"
          ]
        },
        "specification": {
          "$ref": "escrowExecution"
        }
      }
    },
    {
      "properties": {
        "type": {
          "enum": [
            "paymentChannelCreate"
          ]
        },
        "specification": {
          "$ref": "paymentChannelCreate"
        }
      }
    },
    {
      "properties": {
        "type": {
          "enum": [
            "paymentChannelFund"
          ]
        },
        "specification": {
          "$ref": "paymentChannelFund"
        }
      }
    },
    {
      "properties": {
        "type": {
          "enum": [
            "paymentChannelClaim"
          ]
        },
        "specification": {
          "$ref": "paymentChannelClaim"
        }
      }
    }
  ]
}

=== XRPLF/xrpl.js/test/fixtures/responses/get-transaction-escrow-create.json
{
  "type": "escrowCreation",
  "address": "rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh",
  "sequence": 10,
  "id": "144F272380BDB4F1BD92329A2178BABB70C20F59042C495E10BF72EBFB408EE1",
  "specification": {
    "source": {
      "address": "rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh",
      "maxAmount": {
        "currency": "XRP",
        "value": "0.000002"
      },
      "tag": 1
    },
    "destination": {
      "address": "rp8rJYTpodf8qbSCHVTNacf8nSW8mRakFw",
      "amount": {
        "currency": "XRP",
        "value": "0.000002"
      },
      "tag": 2
    },
    "memos": [
      {
        "type": "x2",
        "format": "text/plain",
        "data": "mema data"
      }
    ],
    "condition": "8F434346648F6B96DF89DDA901C5176B10A6D83961DD3C1AC88B59B2DC327AA4",
    "allowCancelAfter": "2015-11-16T06:53:42.000Z",
    "allowExecuteAfter": "2015-11-16T06:47:42.000Z"
  },
  "outcome": {
    "result": "tesSUCCESS",
    "timestamp": "2015-11-16T06:43:00.000Z",
    "fee": "0.000012",
    "balanceChanges": {
      "rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh": [
        {
          "currency": "XRP",
          "value": "-0.000014"
        }
      ]
    },
    "orderbookChanges": {},
    "ledgerVersion": 15,
    "indexInLedger": 0
  }
}

=== XRPLF/xrpl.js/test/fixtures/responses/get-transaction-order-sell.json
{
  "type": "order",
  "address": "rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh",
  "sequence": 2,
  "id": "458101D51051230B1D56E9ACAFAA34451BF65FA000F95DF6F0FF5B3A62D83FC2",
  "specification": {
    "direction": "sell",
    "quantity": {
      "currency": "USD",
      "value": "10.1",
      "counterparty": "rMH4UxPrbuMa1spCBR98hLLyNJp4d8p4tM"
    },
    "totalPrice": {
      "currency": "XRP",
      "value": "254391353"
    }
  },
  "outcome": {
    "result": "tecUNFUNDED_OFFER",
    "timestamp": "2015-11-18T20:56:30.000Z",
    "fee": "0.000012",
    "balanceChanges": {
      "rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh": [
        {
          "currency": "XRP",
          "value": "-0.000012"
        }
      ]
    },
    "orderbookChanges": {},
    "ledgerVersion": 6,
    "indexInLedger": 0
  }
}

=== XRPLF/xrpl.js/test/fixtures/responses/get-transaction-payment-channel-create-with-memo.json
{
  "type": "paymentChannelCreate",
  "address": "rfAuMkVuZQnQhvdMcUKg4ndBb9SPDhzNmK",
  "sequence": 113,
  "id": "0E9CA3AB1053FC0C1CBAA75F636FE1EC92F118C7056BBEF5D63E4C116458A161",
  "specification": {
    "amount": "1",
    "destination": "rBmNDZ7vbTCwakKXsX3pDAwDdQuxM7yBRa",
    "sourceTag": 3444675312,
    "publicKey": "EDE059A23CBE00BDD465910EBDA67C86BAD046FA52E1BBBB27159E31980BAFEFB9",
    "settleDelay": 90000,
    "memos": [
      {
        "type": "test",
        "format": "text/plain",
        "data": "texted data"
      }
    ]
  },
  "outcome": {
    "result": "tesSUCCESS",
    "timestamp": "2017-03-09T14:09:50.000Z",
    "fee": "0.000012",
    "balanceChanges": {
      "rfAuMkVuZQnQhvdMcUKg4ndBb9SPDhzNmK": [
        {
          "currency": "XRP",
          "value": "-1.000012"
        }
      ]
    },
    "orderbookChanges": {},
    "ledgerVersion": 786309,
    "indexInLedger": 0,
    "channelChanges": {
      "status": "created",
      "channelId": "43904CBFCDCEC530B4037871F86EE90BF799DF8D2E0EA564BC8A3F332E4F5FB1",
      "source": "rfAuMkVuZQnQhvdMcUKg4ndBb9SPDhzNmK",
      "destination": "rBmNDZ7vbTCwakKXsX3pDAwDdQuxM7yBRa",
      "channelAmountDrops": "1000000",
      "channelBalanceDrops": "0"
    }
  }
}

=== XRPLF/xrpl.js/test/fixtures/responses/get-transaction-payment-channel-fund-with-memo.json
{
  "type": "paymentChannelFund",
  "address": "rfAuMkVuZQnQhvdMcUKg4ndBb9SPDhzNmK",
  "sequence": 114,
  "id": "CD053D8867007A6A4ACB7A432605FE476D088DCB515AFFC886CF2B4EB6D2AE81",
  "specification": {
    "channel": "43904CBFCDCEC530B4037871F86EE90BF799DF8D2E0EA564BC8A3F332E4F5FB1",
    "amount": "1",
    "memos": [
      {
        "type": "test",
        "format": "text/plain",
        "data": "texted data"
      }
    ]
  },
  "outcome": {
    "result": "tesSUCCESS",
    "timestamp": "2017-03-09T14:09:51.000Z",
    "fee": "0.000012",
    "balanceChanges": {
      "rfAuMkVuZQnQhvdMcUKg4ndBb9SPDhzNmK": [
        {
          "currency": "XRP",
          "value": "-1.000012"
        }
      ]
    },
    "orderbookChanges": {},
    "ledgerVersion": 786310,
    "indexInLedger": 1,
    "channelChanges": {
      "status": "modified",
      "channelId": "43904CBFCDCEC530B4037871F86EE90BF799DF8D2E0EA564BC8A3F332E4F5FB1",
      "source": "rfAuMkVuZQnQhvdMcUKg4ndBb9SPDhzNmK",
      "destination": "rBmNDZ7vbTCwakKXsX3pDAwDdQuxM7yBRa",
      "channelAmountChangeDrops": "1000000",
      "channelAmountDrops": "2000000",
      "channelBalanceDrops": "801000",
      "previousTxnId": "81B9ECAE7195EB6E8034AEDF44D8415A7A803E14513FDBB34FA984AB37D59563"
    }
  }
}

=== XRPLF/xrpl.js/test/fixtures/responses/get-transactions-one.json
[
  {
    "type": "settings",
    "address": "r9UHu5CWni1qRY7Q4CfFZLGvXo2pGQy96b",
    "sequence": 491,
    "id": "D868CFF0DF8C8AAF205404460EA764ACB3B8862527FA414BC8C1CA9A45B1F276",
    "specification": {
      "domain": "ripple.com"
    },
    "outcome": {
      "result": "tesSUCCESS",
      "timestamp": "2015-10-23T02:07:00.000Z",
      "fee": "0.012",
      "balanceChanges": {
        "r9UHu5CWni1qRY7Q4CfFZLGvXo2pGQy96b": [
          {
            "currency": "XRP",
            "value": "-0.012"
          }
        ]
      },
      "orderbookChanges": {},
      "ledgerVersion": 16635149,
      "indexInLedger": 4
    }
  }
]
