=== XRPLF/xrpl.js/src/common/schemas/specifications/payment-channel-claim.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "paymentChannelClaim",
  "link": "payment-channel-claim",
  "type": "object",
  "properties": {
    "channel": {
      "$ref": "hash256",
      "description": "256-bit hexadecimal channel identifier."
    },
    "amount": {
      "$ref": "value",
      "description": "XRP balance of this channel after claim is processed."
    },
    "balance": {
      "$ref": "value",
      "description": "Amount of XRP authorized by signature."
    },
    "signature": {
      "$ref": "signature",
      "description": "Signature of this claim."
    },
    "publicKey": {
      "$ref": "publicKey",
      "description": "Public key of the channel's sender"
    },
    "renew": {
      "type": "boolean",
      "description": "Clear the channel's expiration time."
    },
    "close": {
      "type": "boolean",
      "description": "Request to close the channel."
    }
  },
  "required": ["channel"],
  "additionalProperties": false
}

=== XRPLF/xrpl.js/test/fixtures/requests/prepare-payment-channel-claim-close.json
{
  "channel": "C1AE6DDDEEC05CF2978C0BAD6FE302948E9533691DC749DCDD3B9E5992CA6198",
  "balance": "1",
  "amount": "1",
  "signature": "30440220718D264EF05CAED7C781FF6DE298DCAC68D002562C9BF3A07C1E721B420C0DAB02203A5A4779EF4D2CCC7BC3EF886676D803A9981B928D3B8ACA483B80ECA3CD7B9B",
  "publicKey": "32D2471DB72B27E3310F355BB33E339BF26F8392D5A93D3BC0FC3B566612DA0F0A",
  "close": true
}
